# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    user_agent_subscriber:
        class: AppBundle\EventListener\UserAgentSubscriber
        arguments: ["@logger"]
        tags:
            - { name: kernel.event_subscriber }

    app.security.login_form_authenticator:
            class: AppBundle\Security\LoginFormAuthenticator
            autowire: true

    app.doctrine.hash_password_listener:
            class: AppBundle\Doctrine\HashPasswordListener
            autowire: true
            tags:
                - { name: doctrine.event_subscriber }