# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    user_agent_subscriber:
        class: AppBundle\EventListener\UserAgentSubscriber
        arguments: ["@logger"]
        tags:
            - { name: kernel.event_subscriber }
            #~	