# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
<<<<<<< HEAD
    user_agent_subscriber:
        class: AppBundle\EventListener\UserAgentSubscriber
        arguments: ["@logger"]
        tags:
            - { name: kernel.event_subscriber }
            #~	
=======
    app.markdown_transformer:
        class: AppBundle\Service\MarkdownTransformer
        arguments: ['@markdown.parser']

>>>>>>> 132f6ced91f135ccf33edba0670f782615ed8696
